version: 2
updates:
  - package-ecosystem: gomod
    directory: "/cfn-resources"
    schedule:
      interval: weekly
      day: sunday
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
    commit-message:
      prefix: "chore"
