blank_issues_enabled: true
contact_links:
  - name: MongoDB Atlas CloudFormation Resources Beta Feature Request
    url: https://feedback.mongodb.com/ideas?category=7548141186718564699
    about: Request a feature or up-vote an existing suggestion!
  - name: MongoDB Atlas 
    url: https://www.mongodb.com/cloud/atlas
    about: Learn more about MongoDB Atlas
