name: check-copyright
on:
  push:
    branches: [ "master" , "INT**"]
  pull_request:
    branches: [ "master", "INT**" ]
jobs:
  check-copyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: install devtools
         run: | 
           make devtools
      - name: check copyright
        run: ./.github/scripts/check-licenses.sh
        shell: bash
